### ISSUE TITLE
Encoding to Struct fails for Type T when value is 0 or null

### ISSUE THREAD

**Issue by FourShore** [Valentin-Kaiser/go-dbase#43] opened 2022-11-03 17:13 UTC
I have a struct with 
...
PLANCREATE time.Time `json:"PLANCREATE"`
...

in the table some values in the row are 0 or null which fails to convert with the following error:

[dbase] [DEBUG] 2022/11/03 12:09:01 No encoding converter defined, falling back to default (interpreting)
[dbase] [DEBUG] 2022/11/03 12:09:01 Interpreting code page mark...
[dbase] [DEBUG] 2022/11/03 12:09:01 Code page: 0x03 => interpreted: 0x03
[dbase] [DEBUG] 2022/11/03 12:09:01 Reading row: 0 at offset: 7112
[dbase] [DEBUG] 2022/11/03 12:09:01 Converting row data (2021 bytes) to row struct...
[dbase] [DEBUG] 2022/11/03 12:09:01 Skipping 1 row/s, new position: 1
[dbase] [DEBUG] 2022/11/03 12:09:01 Converting row 0 to struct...
[dbase] [DEBUG] 2022/11/03 12:09:01 Converting row 0 to JSON...
[dbase] [DEBUG] 2022/11/03 12:09:01 Converting row 0 to map...
[dbase] [ERROR] 2022/11/03 12:09:01 dbase-table-tostruct-2:parsing time "0" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse "0" as "\""

Is it possible to default the value in the struct when 0 or null is encountered in the table?

Thanks in advance!

**Comment by Valentin-Kaiser** [comment] 2022-11-04 08:09
To convert a dbase entry into a struct, it is converted into a map and then into a JSON string, which is then converted into a struct. There seems to be an error here. I cannot reproduce your error with my test database. If I set a field of type T to null/0, I get "0001-01-01 00:00:00 +0000 UTC". 
Can you provide me with your tables for testing?

**Comment by Valentin-Kaiser** [comment] 2022-11-06 00:26
> Is it possible to default the value in the struct when 0 or null is encountered in the table?

I think it is possible to implement this, what would be the use cases?

**Comment by Valentin-Kaiser** [comment] 2022-11-06 04:29
@FourShore 
I had an error in the conversion of type T (DateTime) fields. The problem should be fixed, can you verify this?

**Comment by FourShore** [comment] 2022-11-10 22:02
Confirmed working as expected. Values are being set as `0001-01-01 00:00:00 +0000 UTC` which is expected.

**Closed** 2022-11-10 23:29 UTC
Labels: bug, enhancement
